### ISSUE TITLE
Exploration: Investigate Graphite developer tool 🔭

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#160]
## Overview

Investigate [Graphite](www.graphite.dev) as a tool to assist with having more developers in a single repository. 

### Tasks

- [x] Answer questions
- [x] Prepare presentation for Developer Team Aggrements (5-10 minutes)
- [x] Present and discuss in Developer Team Agreements meeting

### Questions to answer & Objectives

- [x] Will it assist in having multiple applications (registration, reporting) in a single repo?
- [x] Will it speed up developer time-to-PR?
- [x] Will it speed up PR review time?
- [x] Will it speed up PR submission to merge time?
- [x] How easy is it to integrate into our existing Git process?
- [x] What is the overhead/learning curve to adopt it?
- [x] Will everyone need to adopt it? Will partial adoption be a benefit or a roadblock?
- [x] What existing processes will need to be added to?
- [x] What existing processes will need to be _changed_?

#### Additional context

Graphite is a developer tool layered on top of Git and GitHub. It allows for the use of the [Stacking workflow](https://stacking.dev/), which compliments our existing single-trunk/rebasing workflow. This workflow is free, but the platform also has [merge queue](https://www.aviator.co/blog/what-is-a-merge-queue/) functionality which is paid (amongst other features).

**Comment by joshgamache** [comment]
Research documentation is in sharepoint here: https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EXV8PIZakPhDkI4NSmpTrzAB5iDRs_i_nEHpklri_A_Csw?e=y8uvqN

A demo video has been uploaded into Stream : https://bcgov-my.sharepoint.com/:v:/g/personal/joshua_gamache_gov_bc_ca/EVzykiOx5CpKqD_nk8J9OvQBeJjlxAw0pYk55H6RWOa5lQ?e=cGvzOe

**Comment by joshgamache** [comment]
Due to pricing, we will likely not adopt this tool as a whole group. However, we have a other options we could explore if we want to adopt a _Git stacking_ pattern.
