### ISSUE TITLE
Bring in main layout components from Reg to Monorepo

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#212]
### Description of the Tech Debt
Bring in Header and Footer, plus supporting components into the monorepo

### Tasks

- [ ] Copy `footer` and `header` components from Reg into shared components library `libs/shared/components/src/lib/layout`
- [ ] Import components where they're used in reporting
- [ ] Comment in registration components (where found) where imports should be updated
  - [ ] Create tech debt ticket for Registration

#### Tech Debt Triage

The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

#### Risk Value Scoring:

| Level  | Value                 |
| ------ | --------------------- |
| High   | <div align="center">3 |
| **Medium** | <div align="center">2 |
| Low    | <div align="center">1 |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |   Low   |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |  Medium    |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |  Low     |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |   Medium    |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |   Low    |       |
| <div align="right">**TOTAL SCORE:**                                                                                           |       |       |

**Comment by rdromey** [comment]
@joshgamache to finish refining and then we'll take the tag off

**Comment by joshgamache** [comment]
This will happen over the course of bcgov/cas-obps#258. Closing in lieu of that ticket.
