### ISSUE TITLE
As an developer I want to have a navigable task list component so that i can implement the various report form pages

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#237]
#### Description:

This work involves creating the sidebar tasklist under each section. This ticket captures the creation of the tasklist. Follow-up tickets will have specific items for the tasklist, including #265 and #267 

[Here is a guideline as to how to implement it on Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=9812-1767&t=4183ePbzcioFJo5r-1)

An example of what the final task list can look like: 

![Image](https://github.com/bcgov/cas-reporting/assets/99216375/7e5673f0-767e-4505-9226-36462cc29916)

#### Acceptance Criteria:

Given I am a developer
When I build a report form page
Then I have a shared component for the navigation list .

Given I am a developer
When I use the shared navigation list 
Then I can configure it with individual pages and at least two levels of expandable hierarchy.

Given I am a developer
When I used Shared navigation list 
Then I can mark each individual item with a green checkmark 
And set the link for it.

#### Development Checklist:

- [x] Simple task list implementation: https://github.com/bcgov/cas-registration/blob/develop/bciers/libs/shared/components/src/lib/form/components/TaskList.tsx
- [x] Configuration will be done with JSON. 
- [x] Configuration should contain the link to the pages, page title, checked/unchecked.
- [x] Empty unauthenticated page with only an instance of the task list for demo.
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Blocking

#265 
#267 

#### Notes:

-

**Comment by pbastia** [comment]
This needs to be a configurable component that we can reuse in each reporting section

**Comment by patriciarussellCAS** [comment]
Note from refinement: Break this down into smaller tickets. This ticket will for building the basic task list. Follow-up tickets will include specific items for the task list. We'll also need a ticket for URL navigation.

**Comment by patriciarussellCAS** [comment]
To confirm - are leaving out the green check "status" aspect of the list for now? Will we just focus on the list itself? 
I believe all we need is a Dev checklist here.

**Comment by pbastia** [comment]
Talk to @BCerki and @marcellmueller to discuss the existing code as a starting point

**Comment by suhafa** [comment]
Needs designer review

**Comment by patriciarussellCAS** [comment]
Need the URL to view this :)

**Comment by marcellmueller** [comment]
@patriciarussellCAS https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/demo

**Comment by suhafa** [comment]
So well executed, thanks for your effort Pierre! Here is the designer review:
1. Noticing there is indentation under every parent item, can we remove this completely? It is throwing off vertical alignment
2. The spacing/padding between the green icon and the text is a lot, could we have it halved?
3. The horizontal line between each facility is actually a darker grey (#606060), but it looks nice to have it lighter grey too so I would say we can keep it this way
4. The caret symbol (^) needs to be shrunk down in size to a 10x10px

**Comment by patriciarussellCAS** [comment]
tagging @pbastia - see Suha's notes

**Comment by patriciarussellCAS** [comment]
Created a new design review ticket for this (#299 ) will close this ticket now.
