### ISSUE TITLE
Emission summary does not recalculate when navigating around with the task list after changes

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#448]
#### Describe the Bug:
When navigating via the task list, the emission summary does not recalculate values if there are changes. For example, if I enter emissions in a couple activities, get to the emission summary page. Then go back via the task list & change a gas type somewhere in one of the activity emissions then go back to the emission summary via the task list. The calculations on the summary page have not updated to reflect the change. If you refresh the page, the values are correct, but it seems navigating with the task list is not triggering a re-render or fetch somewhere.

#### Steps to reproduce the behaviour:

1. enter some emissions in the activity data
2. get to the emission summary page & take note of the values
3. navigate back to an activity & change some emission values (or the gas type values, which will change the equivalent emission values)
4. navigate back to the emission summary page
5. see that the values have not been updated
6. refresh the page. The values have been updated

-

**Comment by patriciarussellCAS** [comment]
Moving this to Sprint 28 so it's top of mind and we can discuss priority level.

**Comment by patriciarussellCAS** [comment]
@fviduya to retest to see if this is still an issue.

**Comment by pbastia** [comment]
Possible investigation path: NextJS server-side actions to fetch data, and "revalidate_path"

**Comment by gdalcengio** [comment]
> Possible investigation path: NextJS server-side actions to fetch data, and "revalidate_path"

adding a revalidationPath to activity form's save handler fixes both this ticket and [590](https://github.com/bcgov/cas-reporting/issues/590)

**Comment by fviduya** [comment]
I have tested this in the DEV environment, [here is the test document for reference](https://buttoninc-my.sharepoint.com/:w:/g/personal/francesca_button_is/EWmLl-_GyU1BrY-NfmxY_uABLptVnnOtrqwuMA5qyvyUbQ?e=I3AEB0).

I can verify that:
- [x] The emissions in the activity form reflect in the Emissions Summary page
- [x] When changing the fuel to a woody biomass classification, the Emissions Summary page reflects the correct values in `Emissions attributable for reporting threshold` field
- [x] When changing the emissions in the activity forms, the Emissions Summary page reflects the correct values
- [x] When removing a unit in an activity form, the emissions from that unit are not counted in the Emissions Summary page

Moving to Pending PO for review of test. Thank you!

**Comment by patriciarussellCAS** [comment]
Test document reviewed. Moving to accepted. Thanks!
