### ISSUE TITLE
Review roadmap to include UX design work for reporting work

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#51]
#### Describe the task

We need to review the roadmap to put down what the first cycle of UI/UX work will look like for reporting work. We have some ideas on stretching out lo-fidelity work first, as well as some iteration for the design process in general.

#### Acceptance Criteria

- [ ] Review existing roadmap
- [ ] create a rough plan for how we want to tackle design process for reporting
- [ ] Amend existing roadmap to have latest design process

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/51?planning-poker) with Zenhub @jaimiebutton @suhafa

**Comment by suhafa** [comment]
@patriciarussellCAS hey Patricia! This ticket is completed. I've amended the roadmap to include UX work for reporting that aligns with [this process](https://miro.com/app/board/o9J_klH4Omo=/?moveToWidget=3458764573141126523&cot=14)

**Comment by patriciarussellCAS** [comment]
Thanks Suha!
