### ISSUE TITLE
Initialize backend

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#68]
_I want_ to set up basic modules in Python for Django and related 
_because_ there is currently no backend
_and this will help me to_ have a base from which the backend will be built congruent with cas-registration.

**Acceptance criteria**:

- [x] Backend 'hello world' application api runs.

## Consideration and notes

- See [Task/updated initial backend setup/15 by Sepehr-Sobhani · Pull Request #49 · bcgov/cas-registration (github.com)](https://github.com/bcgov/cas-registration/pull/49) for implementation on cas-registration.

## Tasks

- [x] Install and configure Poetry
- [x] Django & Django-ninja
- [x] .env file (and env.example) for storing local settings (e.g., connecting to local database)
- [x] Python linting & formatting using Black
- [x] Initialize base api endpoint
- [x] Initialize basic unit test
- [x] Establish subfolder structure
- [x] readme w/ instructions for local installation/development

**Comment by pbastia** [comment]
Are we using Django 5 for this?
