### ISSUE TITLE
Initialize frontend

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#69]
_I want_ to set up basic modules in NodeJS for NextJS, MUI and related 
_because_ there is currently no frontend
_and this will help me to_ have a base from which the front end will be built congruent with cas-registration.

**Acceptance criteria**:

- [ ] Frontend 'hello world' application can be reached.

## Consideration and notes

- See [Technical Debt: Next.js legacy components and folder structure by shon-button · Pull Request #115 · bcgov/cas-registration (github.com)](https://github.com/bcgov/cas-registration/pull/115) for implementation on cas-registration, following the NextJS 14 App directory structure. [18: front end setup by BCerki · Pull Request #23 · bcgov/cas-registration (github.com)](https://github.com/bcgov/cas-registration/pull/23) is the initial front-end setup commit. 

## Tasks

- [x] Install and configure node
- [x] NextJS 14 in App Directory configuration
- [x] .env file (and env.example) for storing local settings (e.g., connecting to local database)
- [x] TailwindCSS package configured in line with reg
- [x] TypeScript installed and configured
