### ISSUE TITLE
Create rough reporting 'roadmap'

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#7]
What's coming up over the next quarter for reporting? Let's put on our thinking caps and create a rough roadmap to align our thinking.

Acceptance Criteria:
- [x] Schedule time with POs (+ SMs optional)
- [x] Create draft reporting roadmap
- [x] Ideate when we would like to have User Stories created
- [x] Ideate when we would like to have MVP created
- [x] Pass roadmap to scrum team for feedback
- [x] Iterate on feedback if needed

Goal of ticket:
 - Get an idea of what to plan for next sprint
 - Do some rough work ahead of Q3 Roadmap planning

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-reporting/7?planning-poker) with Zenhub @nanyangpro @NicoleGovvy

**Comment by patriciarussellCAS** [comment]
Done.
