### ISSUE TITLE
Move away from Django dev WSGI server

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#89]
https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49835390

**Dev Story**:
_I want_ to replace the Django WSGI server with Gunicorn
_because_ it is not intended to be used in production
_and this will help me to_  enhance the performance, security, and scalability of our Django application in the production environment.

**Acceptance criteria**:

1. Backend server runs on Gunicorn rather than Django-dev.

## Consideration and notes

- See [cas-reg #513](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49835390) and the PR https://github.com/bcgov/cas-registration/pull/575 for Cas-reg context.

## Tasks

- [ ] Add Gunicorn to poetry-python dependencies
- [ ] Update backend dockerfile to run Gunicorn server instead of `python manage.py runserver`
- [ ] Update django settings to differentiate debug mode

**Comment by joshgamache** [comment]
Check https://github.com/bcgov/cas-registration/pull/689 for additional changes to make when taking care of this debt.

**Comment by pbastia** [comment]
Closing this! With the monorepo, the single backend already uses gunicorn.
cc @patriciarussellCAS @joshgamache
